node {
  stage('SCM') {
    checkout scm
  }
  stage('SonarQube Analysis') {
    withSonarQubeEnv() {
      sh "pwd"
      sh "cd BackEnd/SOA"
      sh "pwd"
      sh "chmod +x gradlew"
      sh "pwd"
      sh "./gradlew sonar"
      sh "pwd"
    }
  }
}
