node {
  stage('SCM') {
    checkout scm
  }
  stage('SonarQube Analysis') {
    dir('BackEnd/SOA') {
      withSonarQubeEnv() {
        sh "pwd"
        sh "chmod +x gradlew"
        sh "./gradlew sonar"
      }
    }
  }
}
